[package]
name = "trading-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
n9-core = { path = "../../substance/n9-core" }
n9-exchange = { path = "../exchange" }
n9-kit = { path = "../../substance/n9-kit" }
async-trait = "0.1"
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
schemars = "0.8"
